var appVue = new Vue({
    el: '#appVue',
    data: {
        Home: 'Home',
        Home1: 'Home - Image',
        Home2: 'Home - Header Slider',
        Home3: 'Home - Video Background',
        Home4: 'Home - Parallax',
        Home5: 'Home - Scroll Animation',

        Menu: 'Menu',
        Menu1: 'Menu - List',
        Menu2: 'Menu - Overlay',
        Menu3: 'Menu - Tile',
        Menu4: 'Menu - Grid',
        Menu5: 'Menu All',

        Reservation: 'Reservation',
        Reservation1: 'Reservation',
        Reservation2: 'Reservation - Opentable',

        Pages: 'Pages',
        Pages1: 'About',
        Pages2: 'Gallery',
        Pages3: 'Shortcodes',
        Pages4: 'Login / Signup',
        Pages5: '404 Page',

        Recipe: 'Recipe',
        Recipe1: 'Recipe - 2Col',
        Recipe2: 'Recipe - 3Col',
        Recipe3: 'Recipe - 4Col',
        Recipe4: 'Recipe - Masonry',
        Recipe5: 'Recipe - Single',
        Recipe6: 'Recipe - Image',
        Recipe7: 'Recipe - Gallery',
        Recipe8: 'Recipe - Video',

        Blog: 'Blog',
        Blog1: 'Blog - Right Sidebar',
        Blog2: 'Blog - Left Sidebar',
        Blog3: 'Blog - Fullwidth',
        Blog4: 'Blog - Masonry',
        Blog5: 'Blog - Single',
        Blog6: 'Blog - Image',
        Blog7: 'Blog - Gallery',
        Blog8: 'Blog - Video',

        Shop: 'Shop',
        Shop1: 'Shop - Full',
        Shop2: 'Shop - Left Sidebar',
        Shop3: 'Shop - Right Sidebar',
        Shop4: 'Shop - Single',
        Shop5: 'Shop - Full',
        Shop6: 'Shop - Left Sidebar',
        Shop7: 'Shop - Right Sidebar',
        Shop8: 'Shop - Cart',
        Shop9: 'Shop - Checkout',
        Shop10: 'Shop - Account',
        Shop11: 'Shop - Account Detail',

        Contact: 'Contact',

        Number: '3',
        Shopping: 'Shopping Cart',
        Desc: 'Breakfast with coffee',
        Price: '$19.99',
        Quantity: 'x 2',
        Desc1: 'Chicken stew',
        Price1: '$24.99',
        Quantity1: 'x 3',
        Price2: '$ 114.95',
        View: 'View Cart',

        img: 'images/nav-logo.png',
    }
});